// <auto-generated />
using System;
using DATteam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DATteam.Migrations
{
    [DbContext(typeof(DATContext))]
    [Migration("20190619112249_migracija")]
    partial class migracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DATteam.Models.Osoba", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Osoba");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Osoba");
                });

            modelBuilder.Entity("DATteam.Models.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cijena");

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.Property<string>("Proizvodjac");

                    b.Property<int?>("RacunId");

                    b.Property<int>("kolicnia");

                    b.Property<string>("lijekTip");

                    b.Property<bool>("naRecept");

                    b.Property<DateTime>("rokTrajanja");

                    b.HasKey("Id");

                    b.HasIndex("RacunId");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("DATteam.Models.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Narucilacid");

                    b.Property<DateTime>("datumKreiranja");

                    b.HasKey("Id");

                    b.HasIndex("Narucilacid");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("DATteam.Models.Menadzer", b =>
                {
                    b.HasBaseType("DATteam.Models.Osoba");


                    b.ToTable("Menadzer");

                    b.HasDiscriminator().HasValue("Menadzer");
                });

            modelBuilder.Entity("DATteam.Models.Radnik", b =>
                {
                    b.HasBaseType("DATteam.Models.Osoba");


                    b.ToTable("Radnik");

                    b.HasDiscriminator().HasValue("Radnik");
                });

            modelBuilder.Entity("DATteam.Models.Proizvod", b =>
                {
                    b.HasOne("DATteam.Models.Racun")
                        .WithMany("stavkeRacuna")
                        .HasForeignKey("RacunId");
                });

            modelBuilder.Entity("DATteam.Models.Racun", b =>
                {
                    b.HasOne("DATteam.Models.Radnik", "Narucilac")
                        .WithMany()
                        .HasForeignKey("Narucilacid");
                });
#pragma warning restore 612, 618
        }
    }
}
